### ISSUE TITLE
Typo in ˋeval_mini_batch_machine_learning_machine_learningˋ

### ISSUE THREAD

**Issue by olafmersmann** [sequential-parameter-optimization/pyspotstream#5]
Strike one ˋmachine_learningˋ from the name [here](https://github.com/sequential-parameter-optimization/pyspotstream/blob/dad775c95a506d8e8124b9a43c5b25e3adbc61dd/pyspotstream/eval/evaluation.py#L157)?

**Comment by bartzbeielstein** [comment]
Yes, should be fixed in v0.1.12

**Comment by olafmersmann** [comment]
Fixed with e6589354d8bec853fcfd0f2655f9bede599d0972
